name: Testing
on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'docs/**'
      - '*.rst'
      - '.readthedocs.yaml'
      - 'LICENSE'
    tags-ignore: ["*"]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    container:
      image: python:${{ matrix.python }}-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create environment
        run: |
          pip install hatch
          hatch dep show requirements --all >requirements.txt
          pip install -r requirements.txt
          pip install .

      - name: Lint
        run: |
          flake8 docs sprockets examples.py tests.py
          yapf -dr docs sprockets examples.py tests.py

      - name: Test
        run: coverage run -m pytest tests.py

      - name: Output coverage
        run: coverage report && coverage xml

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        if: github.event_name == 'push' && github.repository == 'sprockets/sprockets.http'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
